global:
  scrape_interval: 5s
  external_labels:
    monitor: 'disk-monitor'

rule_files:
  - 'alert.rules'

scrape_configs:
  - job_name: 'prometheus'
    static_configs: 
      - targets: ['10.230.243.253:9090']

  - job_name: 'node-exporter'
    static_configs: 
      - targets: ['10.230.243.253:9100']

  - job_name: 'cadvisor'
    static_configs:
      - targets: ['10.230.243.253:8080']

alerting:
  alertmanagers:
  - scheme: http
    static_configs:
    - targets:
      - "10.230.243.253:9093"
